<Project Sdk="Microsoft.NET.Sdk">

<ItemGroup>
  <PackageReference Include="Microsoft.AspNet.SignalR.Client" Version="2.4.3" />
  <PackageReference Include="Microsoft.AspNet.SignalR.JS" Version="2.4.3" />
  <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
  <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
  <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
  <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="10.0.0" />
</ItemGroup>

<ItemGroup>
    <ProjectReference Include="..\ShoesShop.Crosscutting\ShoesShop.Crosscutting.csproj" />
</ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
